FROM node:alpine AS builder

WORKDIR /app

COPY . .

RUN rm -rf dir /app/node_modules

RUN npm install && \
	npm install --save rxjs-compat && \
    npm run build

FROM nginx:alpine

COPY --from=builder /app/dist/* /usr/share/nginx/html/
